image: leogloria/infnet-gitlab

cache:
  - paths:
    - ./m2/repository

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Compilando codigo..."
    - "mvn clean compile"
  artifacts:
    paths:
      - target/

test-junit-job:
  stage: test
  dependencies:
    - build-job

  script: 
    - echo "Testando codigo.."
    - "mvn package"

  artifacts:
    paths:
      - target/
